id: A434D0152
title: Prayer to Smṛtijñānakīrti
type: translation
pechas:
- IDA7D384F
- IC82C53CC
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:10:14.701882
  last_modified_at: 2023-01-04 13:10:14.701890
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IDA7D384F/B51B: C493
  IC82C53CC/22FA: C493
